### ISSUE TITLE
require 'bowser/http'

### ISSUE THREAD

**Issue by fazibear** [clearwater-rb/bowser#2]
Requiring `browser/http` is not enough, you need to require also `bowser/event_target` witch can be fixed quick.

**Comment by jgaskins** [comment]
I thought `bowser/event_target` was loaded by requiring `bowser`.

I think there was a weird 3-way circular dependency between `Event`, `EventTarget`, and `Window` / `Document` that kept it from being able to be loaded explicitly by one of them. I can't remember off the top of my head.

**Comment by fazibear** [comment]
Sure, but if I want require only `http` module ? You can require `bowser/event_target` few times. Its not a problem.

**Comment by jgaskins** [comment]
Yeah, I very much prefer to require all dependencies of the current file. I probably just overlooked it here. I was just kinda thinking out loud about it, tbh. :-)

**Comment by jgaskins** [comment]
Fixed in 894838ef5d48601496a11d0c8e1b4cbf7d2fb490
