### ISSUE TITLE
add #method_missing to Bowser::Window to fall back to native properties

### ISSUE THREAD

**Issue by balmoral** [clearwater-rb/bowser#21]
Request to add #method_missing to Bowser::Window that falls back to native properties, same as Clearwater::Component.

**Comment by jgaskins** [comment]
Your timing on this is pretty great, tbh. I just extracted the `Bowser::Element#method_missing` to a module in #19 specifically so I could include it into `window` and `document`. 😃

**Comment by balmoral** [comment]
As always your service is better than prompt! 😃
